### ISSUE TITLE
Adding Shaped Anvil Recipe causes crash

### ISSUE THREAD

**Issue by Kacpros** [Sirse/MineFantasyII-Cont#32]
script that im using:
import mods.minefantasy.Anvil;

val leather = <minecraft:leather>;
val stick = <minecraft:stick>;
val dwarfSteel = <lotr:item.dwarfSteel>;

Anvil.addShapedRecipe(<lotr:item.swordDwarven>, "artisanry", "", true, 10.0, "hammer", 3, 3, 10, [<minecraft:leather>, dwarfSteel, <minecraft:stick>, dwarfSteel, dwarfSteel, dwarfSteel]);

Here is the crash report:
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 16.06.18 22:55
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at minefantasy.mf2.integration.minetweaker.helpers.TweakedShapedAnvilRecipe.matches(TweakedShapedAnvilRecipe.java:97)
	at minefantasy.mf2.api.crafting.anvil.CraftingManagerAnvil.findMatchingRecipe(CraftingManagerAnvil.java:254)
	at minefantasy.mf2.block.tileentity.TileEntityAnvilMF.getResult(TileEntityAnvilMF.java:663)
	at minefantasy.mf2.block.tileentity.TileEntityAnvilMF.updateCraftingData(TileEntityAnvilMF.java:669)
	at minefantasy.mf2.block.tileentity.TileEntityAnvilMF.func_145845_h(TileEntityAnvilMF.java:222)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at minefantasy.mf2.integration.minetweaker.helpers.TweakedShapedAnvilRecipe.matches(TweakedShapedAnvilRecipe.java:97)
	at minefantasy.mf2.api.crafting.anvil.CraftingManagerAnvil.findMatchingRecipe(CraftingManagerAnvil.java:254)
	at minefantasy.mf2.block.tileentity.TileEntityAnvilMF.getResult(TileEntityAnvilMF.java:663)
	at minefantasy.mf2.block.tileentity.TileEntityAnvilMF.updateCraftingData(TileEntityAnvilMF.java:669)
	at minefantasy.mf2.block.tileentity.TileEntityAnvilMF.func_145845_h(TileEntityAnvilMF.java:222)

-- Block entity being ticked --
Details:
	Name: MF_Anvil // minefantasy.mf2.block.tileentity.TileEntityAnvilMF
	Block type: ID #1041 (tile.anvilSteel // minefantasy.mf2.block.crafting.BlockAnvilMF)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (244,72,53), Chunk: (at 4,4,5 in 15,3; contains blocks 240,0,48 to 255,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1041 (tile.anvilSteel // minefantasy.mf2.block.crafting.BlockAnvilMF)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['KacperKubus'/342, l='New World', x=243,70, y=72,00, z=53,42]]
	Chunk stats: ServerChunkCache: 330 Drop: 0
	Level seed: 3447552771013305714
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (220,64,72), Chunk: (at 12,4,8 in 13,4; contains blocks 208,0,64 to 223,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13080 game time, 13080 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 94849 (now: false), thunder time: 42750 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Sirse** [comment]
I will release a fixed version on this week

**Comment by Kacpros** [comment]
is an update already released?
